accton-as4610: fix value truncation when accessing leds
Some leds, namely PSU1/2 and FAN support the mode
LED_MODE_AUTO_BLINKING. This mode has the numeric value of 10, which
requires 2 bytes to represent as a string.

Currently the code assumes that the maximum length is 1, and this
results in truncation when trying to set this mode, or reading out this
mode.

Fix this by increasing the buffers to 3 bytes, and adapting the
setter and getter to handle these values.

$ cat /sys/devices/platform/as4610_led/leds/as4610\:\:fan/brightness
10

Before:

   led @ 11 = {
       Description: fan
       Status: 0x00000001 [ PRESENT ]
       Caps:   0x00c00000 [ AUTO,AUTO_BLINKING ]
       Mode: OFF
       Char:
   }

After:

   led @ 11 = {
       Description: fan
       Status: 0x00000005 [ PRESENT,ON ]
       Caps:   0x00c00000 [ AUTO,AUTO_BLINKING ]
       Mode: AUTO_BLINKING
       Char:
   }

Found by GCC 9.3:

|     Compiling[ release ]: arm_accton_as4610::ledi.c
| git/packages/platforms/accton/armxx/arm-accton-as4610/arm_accton_as4610/module/src/ledi.c: In function 'onlp_ledi_mode_set':
| git/packages/platforms/accton/armxx/arm-accton-as4610/arm_accton_as4610/module/src/ledi.c:431:37: error: '__builtin___snprintf_chk' output may be truncated before the last format character [-Werror=format-truncation=]
|   431 |     snprintf(data, sizeof(data), "%d", driver_mode);
|       |
| In file included from recipe-sysroot/usr/include/stdio.h:867,
|                  from git/sm/infra/modules/AIM/module/inc/AIM/aim_porting.h:40,
|                  from git/sm/infra/modules/AIM/module/inc/AIM/aim_config.h:310,
|                  from git/sm/infra/modules/AIM/module/inc/AIM/aim.h:34,
|                  from git/packages/base/any/onlp/src/onlp/module/inc/onlp/onlp_config.h:46,
|                  from git/packages/base/any/onlp/src/onlp/module/inc/onlp/onlp.h:28,
|                  from git/packages/base/any/onlp/src/onlp/module/inc/onlp/led.h:28,
|                  from git/packages/base/any/onlp/src/onlp/module/inc/onlp/platformi/ledi.h:28,
|                  from git/packages/platforms/accton/armxx/arm-accton-as4610/arm_accton_as4610/module/src/ledi.c:26:
| recipe-sysroot/usr/include/bits/stdio2.h:67:10: note: '__builtin___snprintf_chk' output between 2 and 3 bytes into a destination of size 2
|    67 |   return __builtin___snprintf_chk (__s, __n, __USE_FORTIFY_LEVEL - 1,
|       |          ^~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
|    68 |        __bos (__s), __fmt, __va_arg_pack ());
|       |        ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
| cc1: all warnings being treated as errors

Signed-off-by: Jonas Gorski <jonas.gorski@bisdn.de>